name = "NGRCraft"
author = "Nuts"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1323b7618dc333737a438d22f899039f7ce2bc579b7fbaa937fd04024498b4d"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
